### ISSUE TITLE
Exadata Real Time Insight actual tutorials

### ISSUE THREAD

**Issue by raulk89** [oracle-samples/oracle-db-examples#219]
Hi

Using exadata cloud at customer 22.1
I was wondering, is there an actual tutorials , how can I configure real time insight.

I am well aware of these, but these link, but these are not actual tutorials, these are very laconic, and not much help.
https://github.com/oracle-samples/oracle-db-examples/tree/main/exadata/insight/dashboard_grafana_prometheus
https://blogs.oracle.com/exadata/post/exadata-real-time-insight

Regards
Raul

**Comment by alex-blyth-pm** [comment]
This quick start should give you a leg up on Real-Time Insight. There is a blog forthcoming that will explain the quick start, but hopefully this might get you going sooner.
