### ISSUE TITLE
How to enter connection string in prompt?

### ISSUE THREAD

**Issue by donhuvy** [oracle-samples/oracle-db-examples#227]
I read guide at https://docs.oracle.com/database/121/COMSC/installation.htm#COMSC00005 . But the guide did not guide me how to enter connection string.

![image](https://user-images.githubusercontent.com/1328316/203265779-c797cd81-e193-4585-992b-4f6908f44ba6.png)

My question also at here: https://stackoverflow.com/questions/74529518/how-to-enter-connection-string-when-install-hr-sample-schema

**Comment by gvenzl** [comment]
Please use the sample schemas provided under https://github.com/oracle-samples/db-sample-schemas and follow the ReadMe instructions there.
