### ISSUE TITLE
Add code and configuration examples for continuous application availability

### ISSUE THREAD

**Issue by lcaldara-oracle** [oracle-samples/oracle-db-examples#278]
Oracle has created a new guide to implementing continuous availability for the applications:
https://docs.oracle.com/en/database/oracle/oracle-database/19/haovw/configuring-continuous-availability-applicationsconfiguring-continuous-availability-applicatio.html

The documentation replaces the whitepaper "Application Checklist for Continuous Service for MAA Solutions."

The whitepaper now reflects the new documentation:
https://www.oracle.com/docs/tech/application-checklist-for-continuous-availability-for-maa.pdf

As part of this effort, we must add examples that help implement end-to-end high availability using Oracle Maximum Availability Architecture technologies.

Examples must include:
* A new folder, "continuous-availability," with examples and snippets common to all programming languages:
  * Services for Application Continuity and Transparent Application Continuity, with and without Clusterware
  * Explanation and connection descriptor examples for Oracle Real Application Clusters, Data Guard, Autonomous DB, in extended form and EZConnectPlus
* Code examples for each language, to be added to their respective folders
* Occasional changes to existing examples, if needed

As the changes might span over multiple pull requests, I create this issue to track the addition of the aforementioned examples to this repository.

**Comment by gvenzl** [comment]
Housekeeping, please reopen if required.
