### ISSUE TITLE
Prometheus scrape configuration to get real-time insight metrics into Prometheus

### ISSUE THREAD

**Issue by ddilyard** [oracle-samples/oracle-db-examples#304]
The dashboards for Exadata's real-time insights looks great, however, how are these metrics being consumed by Prometheus? 

I'd love to see the scrape_configs in prometheus.yml for your Exadata targets. Is this being scraped directly using the API or is there a bridge in between?

**Comment by alex-blyth-pm** [comment]
Take a look at this prometheus.yml file - https://github.com/oracle-samples/oracle-db-examples/blob/main/exadata/insight/quick_start/container/prometheus/prometheus.yml

This is part of a quick start guide being published shortly and will be updated regularly.
