### ISSUE TITLE
jdbc sample context.xml missing quote

### ISSUE THREAD

**Issue by radioalarm** [oracle-samples/oracle-db-examples#323]
The file https://github.com/oracle-samples/oracle-db-examples/blob/main/java/jdbc/Tomcat_Servlet/META-INF/context.xml is missing a closing quote on line 21.

**Comment by gvenzl** [comment]
Thanks a lot for reporting this, @radioalarm!

@Kuassim, @jeandelavarene, please take a look and provide a PR with a fix.
